import type { Metadata } from "next";
import { Inter, Inter_Tight } from "next/font/google";
import AdminNavbar from "@/components/admin/AdminNavbar";
// import AdminSidebar from "@/components/admin/AdminSidebar";
import "@/app/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";

const inter = Inter({
  subsets: ["latin"],
});
const interTight = Inter_Tight({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Wiseways Solutions",
  description: "Generated by create next app",
};

export default function AdminDashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // sm:bg-fuchsia-200 md:bg-amber-200 lg:bg-blue-200 xl:bg-green-300
  return (
    <div className={`${inter.className} ${interTight.className} bg-gray-white antialiased`}>
      <SidebarProvider>
        <div className="flex w-screen">
          {/* <AdminSidebar /> */}
          <div className="flex-1"> 
            <AdminNavbar />
            <main className="mt-36 px-0 md:px-8 lg:px-15 w-full">{children}</main> 
          </div>
        </div>
      </SidebarProvider>
    </div>
  );
}