import type { Metadata } from "next";
import { Inter, Inter_Tight } from "next/font/google";
import AdminSidebar from "@/components/admin/AdminSidebar";
import "@/app/globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const inter = Inter({
  subsets: ["latin"],
});
const interTight = Inter_Tight({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Wiseways Solutions",
  description: "Generated by create next app",
};

export default function AdminDashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${inter.className} ${interTight.className} bg-gray-white antialiased`}
    >
      <SidebarProvider>
        <AdminSidebar />
        <main>
          <SidebarTrigger />
          {children}
        </main>
      </SidebarProvider>
    </div>
  );
}
