import type { Metadata } from "next";
import { Inter, Inter_Tight } from "next/font/google";
import AdminNavbar from "@/components/admin/AdminNavbar";
import AdminSidebar from "@/components/admin/AdminSidebar";
import "@/app/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";

const inter = Inter({
  subsets: ["latin"],
});
const interTight = Inter_Tight({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Wiseways Solutions",
  description: "Generated by create next app",
};

export default function AdminDashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${inter.className} ${interTight.className} bg-gray-white antialiased`}>
      <SidebarProvider>
        <div className="flex">
          <AdminSidebar />
          <div className="flex-1 ml-[250px]"> 
            <AdminNavbar />
            <main className="mt-16 px-6">{children}</main> 
          </div>
        </div>
      </SidebarProvider>
    </div>
  );
}